### ISSUE TITLE
Verify MB and MHz value conversions are correct

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/webgl-gpu-power-estimation#4]

**Comment by gkjohnson** [comment]
Math.js, being used for unit conversion, is the "1000 MB in a GB" convention as opposed to the preferred 1024.

**Comment by AaronPlave** [comment]
For bytes it looks like you'd have to use the binary prefixes specified here: 
http://mathjs.org/docs/datatypes/units.html#reference

Would look like
```
math.unit('8 GiB').toNumber('MiB');
// 8192
```

**Comment by AaronPlave** [comment]
The MHz values look correct from the few spot checks I did.

**Comment by gkjohnson** [comment]
> For bytes it looks like you'd have to use the binary prefixes specified here:
http://mathjs.org/docs/datatypes/units.html#reference

Great so we'll just have to convert the token to match what math expects. Something like this should work:

```js
// 10MB -> 10MiB
// 10 MB -> 10 MiB
memoryToken = token.replace(/([A-Z])B/, (match, prefix) => `${prefix}iB`);
```

Those changes would have to happen here:
https://github.com/gkjohnson/webgl-gpu-power-estimation/blob/master/scripts/fetch-videocard-benchmark.js#L81

And here (the data is comma separated as `11 GB, GDDR6, 352 bit`):
https://github.com/gkjohnson/webgl-gpu-power-estimation/blob/master/scripts/fetch-techpowerup-specs.js#L102

If you want to make the changes go for it otherwise I can take a look later.
