### ISSUE TITLE
Attempt to add mobile benchmark data from notebookcheck

### ISSUE THREAD

**Issue by AaronPlave** [gkjohnson/webgl-gpu-power-estimation#8]
https://www.notebookcheck.net/Mobile-Graphics-Cards-Benchmark-List.844.0.html

**Comment by gkjohnson** [comment]
Looks like all that data is loaded in via the index.html file :(

#### Making the Request

Click `restrict` makes a POST request to:

```
https://dev1.notebook-check.com/index.php?id=844
```

with the following form data (least restrictive checkboxes):
```
search: 
or: 0
deskornote: 2
professional: 0
multiplegpus: 0
month: 
archive: 1
showBars: 1
showClassDescription: 1
perfrating: 1
gpu_fullname: 1
codename: 1
architecture: 1
pixelshaders: 1
vertexshaders: 1
corespeed: 1
shaderspeed: 1
boostspeed: 1
memoryspeed: 1
memorybus: 1
memorytype: 1
directx: 1
opengl: 1
technology: 1
daysold: 1
3dmark13_ice_gpu: 1
3dmark13_cloud: 1
3dmark13_cloud_gpu: 1
3dmark13_fire: 1
3dmark13_fire_gpu: 1
3dmark13_time_spy: 1
3dmark13_time_spy_gpu: 1
3dmark11: 1
3dmark11_gpu: 1
vantage3dmark: 1
vantage3dmarkgpu: 1
3dmark06: 1
3dmark01: 1
glbenchmark: 1
gfxbench30: 1
gfxbench31: 1
basemarkx11_med: 1
basemarkx11_high: 1
heaven3_dx: 1
valley_dx: 1
cb15_ogl: 1
cinebench10_ogl: 1
computemark_result: 1
luxmark_sala: 1
barlength: 0
debug: 
```

or
 
```
search=&or=0&deskornote=2&professional=0&multiplegpus=0&month=&archive=1&showBars=1&showClassDescription=1&perfrating=1&gpu_fullname=1&codename=1&architecture=1&pixelshaders=1&vertexshaders=1&corespeed=1&shaderspeed=1&boostspeed=1&memoryspeed=1&memorybus=1&memorytype=1&directx=1&opengl=1&technology=1&daysold=1&3dmark13_ice_gpu=1&3dmark13_cloud=1&3dmark13_cloud_gpu=1&3dmark13_fire=1&3dmark13_fire_gpu=1&3dmark13_time_spy=1&3dmark13_time_spy_gpu=1&3dmark11=1&3dmark11_gpu=1&vantage3dmark=1&vantage3dmarkgpu=1&3dmark06=1&3dmark01=1&glbenchmark=1&gfxbench30=1&gfxbench31=1&basemarkx11_med=1&basemarkx11_high=1&heaven3_dx=1&valley_dx=1&cb15_ogl=1&cinebench10_ogl=1&computemark_result=1&luxmark_sala=1&barlength=0&debug=
```

#### Parsing the table
The table looks pretty regular with any rows with GPU data having the classes `odd`, `even`, `desk_odd`, or `desk_even`.

#### The Performance Metrics

It might be important to note that the current benchmarks used are from PassMark while those provided at this website are from a slew of other sources. It may be necessary to provide multiple benchmark values. Or find a set of benchmark data that is more complete.

**Comment by AaronPlave** [comment]
Oof. Well, I haven't found any info on how to really relate these different benchmarks so multiple benchmark values may be the only way.

**Comment by gkjohnson** [comment]
I would imagine that the benchmark scores all trend similarly. So as long as we have some cards with scores from across all / multiple performance benchmarks we should be able to map and generate scores of a fitting magnitude for any missing data in one of the benchmarks.

**Comment by gkjohnson** [comment]
I've added the notebookcheck data in #12 so all the mobile graphics data should be available now.

For cards missing the passmark performance benchmark I've [generated a score by interpolating between scores from cards with nearby scores from other benchmarks](https://github.com/gkjohnson/webgl-gpu-power-estimation/blob/master/scripts/generate-normalized-database.js#L141). It's not perfect but it should hopefully give a ballpark performance metric relative to the other cards -- we can talk about it a bit more on Monday.
